http:
  port: :8000
  admin:
    prefix: /admin

db:
  type: mysql
  dbname: tinker
  port: 3306
  host: localhost
  username: root
  password: 123456
  tablePrefix: t_
  logEnable: false

cache:
  type: redis
  host: localhost
  port: 1234
  username: root
  password: root
  # type: gocache
  # size: 104857600